name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Debug - List Build Directory
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      run: |
        echo "Listing the entire build directory to debug"
        ls -l ${{ steps.strings.outputs.build-output-dir }}

    - name: Fix Permissions (Linux/macOS)
      if: runner.os != 'Windows'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      run: chmod +x build/release/debug/vectorvslist  # Correct path for Linux/macOS

    - name: Run Executable
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      run: |
        # Set executable name based on OS
        executable="release/debug/vectorvslist"  # Add debug to the path for Windows/Linux/macOS
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          executable="release/debug/vectorvslist.exe"  # Add .exe for Windows
        fi
        
        # Check if the file exists before trying to run it
        echo "Checking if executable exists: $executable"
        if [ -f "$executable" ]; then
          echo "Executable found, running it"
          ./$executable  # This works for both Windows (Git Bash) and Linux/macOS
        else
          echo "Executable not found: $executable"
          exit 1  # Fail if the executable isn't found
        fi
